### ISSUE TITLE
Upgrade to the latest Kotlin 

### ISSUE THREAD

**Issue by mikegehard** [exercism/kotlin#288]

**Comment by blueglyph** [comment]
I'm not sure why this was open, but I'll use it to comment, sorry if that was not meant for that.

Usually I'm changing the build.gradle setup file like this before using it, to work around the fixed, old Kotlin version. Perhaps this is how it could be set in all exercises?

```
buildscript {
  ext.kotlin_version = '1.+'
  repositories {
    mavenCentral()
  }
  dependencies {
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
  }
} 

```

(instead of specifying the Kotlin version explicitly)

The same can be used for the junit version.

**Comment by mikegehard** [comment]
Thanks for the thoughts @blueglyph. Yeah we need to figure out a way to make the version a bit more flexible as the versions change.

**Comment by dector** [comment]
I guess it's very possible to generate exercises based on some meta-data. :)

**Comment by dector** [comment]
Proof of concept: https://github.com/dector/genercism/blob/master/data/exercises/reverse-string.json

**Comment by dector** [comment]
Folks from Slack pointed me to [problem-specifications](https://github.com/exercism/problem-specifications). Will check it out and probably use it as a source data for generator.

**Comment by dector** [comment]
Generated exercises snapshots are [here](https://github.com/dector/genercism/issues/1). Please, notice that exercises that are using Maps as arguments/return types are not compiling for now.

**Comment by sshine** [comment]
@mikegehard, @uzilan: Just an FYI: If you bump Kotlin version constraints in `build.gradle` you may experience that this change doesn't propagate to the website; see e.g. exercism/haskell#864 for how we deal with it.

@dector wrote:
> I guess it's very possible to generate exercises based on some meta-data. :)

It's nice to see that you're getting acquainted with the Exercism infrastructure and try to expand upon it.

Perhaps the subject of auto-generating exercises based on problem-specifications deserves its own issue, rather than conflate this with bumping the Kotlin version for all existing exercises. (The task of this issue is more tangible and deserves few dependencies.) There are quite a few tracks that have good test generators; C#, F# and OCaml are among them; unfortunately, as it's not something I've dealt with directly, I cannot say what their state of documentation is. (OCaml track's test generator framework had a total makeover recently, but the changes still lack a bit of documentation.)

**Comment by dector** [comment]
@sshine 

> There are quite a few tracks that have good test generators

[I've played a bit with it](https://github.com/dector/genercism/) and came up with few ideas about exercises generation. The side-goal of it is also to check if somebody other want to join efforts to improve exercises meta-data and discuss generic approach/specification for all languages.

> Perhaps the subject of auto-generating exercises based on problem-specifications deserves its own issue, rather than conflate this with bumping the Kotlin version for all existing exercises. 

Of cause, you are right. Just updating Kotlin version in build-files is (relatively). However I see that some exercises are broken (e.g. don't have source files) for quite a long time. I suppose, moving towards generating them is a good way to save time and efforts for human beings. :robot:

Besides generating exercises from `problem-specification` I've already implemented compromised approach that is simpler but requires some attention to init it: generating exercises from kotlin code snippets. [(Look here)](https://github.com/dector/genercism/blob/2b17f9b483fb14679065fd5aead10214a61710bd/data/exercises/reverse-string.json#L6).

To sum-up, my point here is:
a) To start discussion (and probably move soon towards implementation) about generating Kotlin-exercises infrastructure based on code snippets.
b) To start/join discussions about generating exercises for (possibly) all languages from problem specifications.
c) To help maintainers to avoid unnecessary manual work (e.g. automate what can be automated).

**Comment by sshine** [comment]
I should disclaim that I don't participate in the Kotlin track; I am merely responding to @uzilan's comment on Slack on the subject of this pull request wrt. a particular nag that's been documented elsewhere: You have to touch the test file even though your only change affects `build.gradle`.

> However I see that some exercises are broken (e.g. don't have source files) for quite a long time. I suppose, moving towards generating them is a good way to save time and efforts for human beings.

That may well be, but for the sake of separation of concerns, it is possible to upgrade to the latest Kotlin without creating a fully generic exercise generator. If you regard these as separate issues, you can achieve both independently. As the bar for upgrading to the latest Kotlin for all exercises is considerably lower, the track maintainers may want to do this first and regard a potential exercise generator on its own merits in an issue that particularly discusses it.

Otherwise, when "Upgrade to the latest Kotlin" has been accomplished, this issue can be closed, and any reference to a discussion of a tangential topic in this issue would either have to continue in a closed issue (making it less discoverable), or by references from an open issue appropriately named e.g. "Auto-generating exercises in Kotlin".

The Kotlin track maintainers and contributors should feel free to discuss and divide issues in any way they/you like, but this is one suggestion.

**Comment by dector** [comment]
Sure, @sshine what you say totally make sense.

But since I'm new here I just wanted to make **quick-check** :) about what other's people think. However, we are already generating too much meta-discussion - and it make scene to create a separate issue.
